# Generated by Django 5.2.17 on 2026-08-11 22:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Visita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('visitante', models.CharField(db_index=True, max_length=32)),
                ('canal', models.CharField(choices=[('anuncio', 'Anúncio pago'), ('busca', 'Busca orgânica'), ('social', 'Redes sociais'), ('referencia', 'Outros sites'), ('direto', 'Direto')], db_index=True, default='direto', max_length=20)),
                ('origem', models.CharField(blank=True, max_length=120)),
                ('midia', models.CharField(blank=True, max_length=120)),
                ('campanha', models.CharField(blank=True, max_length=180)),
                ('conteudo', models.CharField(blank=True, max_length=180)),
                ('termo', models.CharField(blank=True, max_length=180)),
                ('referencia', models.CharField(blank=True, max_length=300)),
                ('caminho', models.CharField(blank=True, max_length=300)),
                ('dispositivo', models.CharField(choices=[('celular', 'Celular'), ('tablet', 'Tablet'), ('computador', 'Computador')], default='computador', max_length=20)),
                ('agente', models.CharField(blank=True, max_length=300)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('robo', models.BooleanField(db_index=True, default=False)),
            ],
            options={
                'verbose_name': 'visita',
                'verbose_name_plural': 'visitas',
                'ordering': ('-criado_em',),
            },
        ),
        migrations.CreateModel(
            name='Clique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('evento', models.CharField(db_index=True, max_length=40)),
                ('canal', models.CharField(choices=[('anuncio', 'Anúncio pago'), ('busca', 'Busca orgânica'), ('social', 'Redes sociais'), ('referencia', 'Outros sites'), ('direto', 'Direto')], db_index=True, default='direto', max_length=20)),
                ('robo', models.BooleanField(db_index=True, default=False)),
                ('visita', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cliques', to='painel.visita')),
            ],
            options={
                'verbose_name': 'clique',
                'verbose_name_plural': 'cliques',
                'ordering': ('-criado_em',),
            },
        ),
    ]
