# Generated by Django 5.2.17 on 2026-08-12 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clique',
            name='interno',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='visita',
            name='interno',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
