# Generated by Django 5.2.17 on 2026-08-14 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painel', '0002_clique_interno_visita_interno'),
    ]

    operations = [
        migrations.AddField(
            model_name='visita',
            name='medido',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='visita',
            name='rolagem',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='visita',
            name='segundos',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
